### ISSUE TITLE
Block modifier affecting elements

### ISSUE THREAD

**Issue by jeffijoe** [sgtpep/css-modules-html-demo#1]
Say you have `.block___elem` and a `.block--expanded` modifier. In BEM, to affect the elements with the block modifier:

``` css
.block--expanded .block__elem {
  width: 100%
}
```

How are you supposed do to this in CSS modules? 😄
